name: CI
on: push
jobs:
  prod-check:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run cd DjangoBlogApp
      - run  pip install -r requirements.txt
